Controller programa luis escm3
gebraz/ppgs_labprog2023 pull request #32
Opened 2023-05-29 20:01 UTC by luisEscm

2023-05-30 13:25 UTC, gebraz requested changes

2023-05-30 13:25 UTC, gebraz commented on backend/sppg/src/main/java/br/ufma/sppg/service/DocenteService.java
Corrige o teu DocenteService, 
coisas como RegrasRunTime não existem mais

2023-05-30 13:25 UTC, gebraz commented on backend/sppg/src/main/java/br/ufma/sppg/service/ProgramaService.java
Também não está refletindo a situação atual

2023-05-31 20:03 UTC, luisEscm commented on backend/sppg/src/main/java/br/ufma/sppg/service/DocenteService.java
corrigi isso, e também adicionei os métodos de salvar obterDocente usando o id e o método de obterDocentesNome que devolve um lista de docentes com um dado nome.

2023-06-01 17:54 UTC, gebraz approved these changes

2023-06-01 17:55 UTC, merged