Feature/qualis controller
gebraz/ppgs_labprog2023 pull request #35
Opened 2023-05-31 14:48 UTC by felipersteles

2023-05-31 20:46 UTC, gebraz requested changes
Além do application properties, não manda os .class de target

2023-05-31 20:46 UTC, gebraz commented on backend/sppg/src/main/resources/application.properties
Não manda application.properties

2023-06-02 17:44 UTC, felipersteles commented
feito

2023-06-05 14:56 UTC, gebraz approved these changes

2023-06-12 12:26 UTC, felipersteles commented
Tratando as exceções e adicionando uma nova rota que retorna as estatisticas do ppg.

2023-06-12 17:15 UTC, gebraz approved these changes

2023-06-12 17:15 UTC, gebraz commented on backend/sppg/src/main/java/br/ufma/sppg/service/ProgramaService.java
cara, porque tu apagaste ProgramaService?

2023-06-12 17:17 UTC, merged