Controler orientacao urubus do pix
gebraz/ppgs_labprog2023 pull request #38
Opened 2023-06-04 15:42 UTC by jovijovi-john

Endpoints implementados no controller, precisei também implementar as coisas no service e no repository de orientação. Algumas coisas podem ser melhoradas por quem for mexer em orientação depois, porque o service inteiro ta precisando de validação de datas, não tem um tratamento de erro. As funções foram implementadas visando finalizar o controller apenas.

2023-06-05 15:05 UTC, gebraz requested changes
Não manda application.properties e os .class

2023-06-05 15:05 UTC, gebraz commented on backend/sppg/src/main/resources/application.properties
não manda application.properties

2023-06-05 15:05 UTC, gebraz commented on backend/sppg/target/classes/br/ufma/sppg/SppgApplication.class
não manda os arquivos .class

2023-06-05 15:13 UTC, jovijovi-john commented on backend/sppg/src/main/resources/application.properties
essas modificações ai nos arquivos foi removendo eles, professor. No caso eles não estão sendo adicionados não

2023-06-05 15:14 UTC, jovijovi-john commented on backend/sppg/target/classes/br/ufma/sppg/SppgApplication.class
mesma coisa com esses .class

2023-06-05 16:40 UTC, gebraz commented on backend/sppg/src/main/resources/application.properties
Para mim está aparecendo como se tu tivesse removido o conteúdo, mas não o arquivo

2023-06-13 16:52 UTC, gebraz approved these changes

2023-06-13 16:52 UTC, merged