Test service tecnica urubus do pix
gebraz/ppgs_labprog2023 pull request #40
Opened 2023-06-05 03:29 UTC by jovijovi-john

implementação dos testes do service de tecnica, aqui incluem tanto os códigos da dupla urubusDoPix quanto da equipe vascodagama

2023-06-05 15:06 UTC, gebraz requested changes
Não manda arquivos .class

2023-06-05 15:06 UTC, gebraz commented on backend/sppg/target/classes/br/ufma/sppg/SppgApplication.class
não manda arquivos .class

2023-06-12 17:36 UTC, jovijovi-john commented
Professor, resolvi o conflito que tava dando com o DocenteControler, ja que a branch tava desatualizada. É preciso ainda eu fazer alguma coisa pra esse PR funcionar ou tenho q tipo, fechar ele e abrir dnv? kkkk

2023-06-13 16:51 UTC, gebraz approved these changes

2023-06-13 16:51 UTC, merged